/**
 * PitchLab PDF Report Generator
 *
 * Builds a professional, multi-page PDF from an AnalysisResult.
 * Uses jsPDF for native clickable hyperlinks (critical for YouTube drill links).
 */

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { AnalysisResult } from "@/types/analysis";
import { PAGE, COLORS, FONT, gradeColor, statusColor, priorityColor } from "./pdf-styles";

const FOOTER_TEXT = "Generated by PitchLab \u00B7 AI analysis is not a substitute for professional coaching";

// ─── Helpers ────────────────────────────────────────────────────────────────

function addFooter(doc: jsPDF, pageNum: number) {
  const y = PAGE.height - 25;
  doc.setFontSize(FONT.tiny);
  doc.setTextColor(...COLORS.light);
  doc.text(FOOTER_TEXT, PAGE.width / 2, y, { align: "center" });
  doc.text(`Page ${pageNum}`, PAGE.width - PAGE.marginX, y, { align: "right" });
}

function sectionHeader(doc: jsPDF, title: string, y: number): number {
  doc.setFontSize(FONT.h1);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.black);
  doc.text(title, PAGE.marginX, y);

  // Underline accent
  doc.setDrawColor(...COLORS.brand);
  doc.setLineWidth(1.5);
  doc.line(PAGE.marginX, y + 3, PAGE.marginX + 80, y + 3);
  return y + 16;
}

function checkPageBreak(doc: jsPDF, y: number, needed: number, pageNum: { value: number }): number {
  if (y + needed > PAGE.height - PAGE.marginBottom) {
    addFooter(doc, pageNum.value);
    pageNum.value++;
    doc.addPage();
    return PAGE.marginTop;
  }
  return y;
}

// ─── Page 1: Cover ──────────────────────────────────────────────────────────

function renderCover(doc: jsPDF, analysis: AnalysisResult) {
  let y = 50;

  // Brand header
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.black);
  doc.text("PITCH", PAGE.marginX, y);
  const pitchWidth = doc.getTextWidth("PITCH");
  doc.setTextColor(...COLORS.brand);
  doc.text("LAB", PAGE.marginX + pitchWidth, y);

  doc.setFontSize(FONT.small);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.muted);
  doc.text("AI MECHANICS COACH", PAGE.marginX, y + 12);

  // Date
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(dateStr, PAGE.width - PAGE.marginX, y + 12, { align: "right" });

  // Divider
  y += 28;
  doc.setDrawColor(...COLORS.brandLight);
  doc.setLineWidth(0.5);
  doc.line(PAGE.marginX, y, PAGE.width - PAGE.marginX, y);

  // Overall grade badge
  y += 30;
  const gc = gradeColor(analysis.overall_grade);
  const badgeX = PAGE.width / 2;

  // Circle
  doc.setFillColor(...gc);
  doc.circle(badgeX, y, 28, "F");

  // Grade text
  doc.setFontSize(30);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text(analysis.overall_grade, badgeX, y + 10, { align: "center" });

  doc.setFontSize(FONT.small);
  doc.setTextColor(...gc);
  doc.text("OVERALL GRADE", badgeX, y + 40, { align: "center" });

  // Summary
  y += 60;
  doc.setFontSize(FONT.body);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.dark);
  const summaryLines = doc.splitTextToSize(analysis.overall_summary, PAGE.contentWidth);
  doc.text(summaryLines, PAGE.marginX, y);
  y += summaryLines.length * 14;

  // Age note
  if (analysis.pitcher_age_note) {
    y += 4;
    doc.setFontSize(FONT.small);
    doc.setTextColor(...COLORS.muted);
    doc.setFont("helvetica", "italic");
    const ageLines = doc.splitTextToSize(analysis.pitcher_age_note, PAGE.contentWidth);
    doc.text(ageLines, PAGE.marginX, y);
    y += ageLines.length * 12;
  }

  // Encouragement callout box
  if (analysis.encouragement) {
    y += 10;
    const encLines = doc.splitTextToSize(analysis.encouragement, PAGE.contentWidth - 24);
    const boxHeight = encLines.length * 12 + 16;

    doc.setFillColor(...COLORS.brandLight);
    doc.roundedRect(PAGE.marginX, y, PAGE.contentWidth, boxHeight, 4, 4, "F");

    // Blue left bar
    doc.setFillColor(...COLORS.brand);
    doc.rect(PAGE.marginX, y, 3, boxHeight, "F");

    doc.setFontSize(FONT.small);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...COLORS.brand);
    doc.text(encLines, PAGE.marginX + 14, y + 12);
    y += boxHeight;
  }

  // Validation note
  if (analysis.validation_confidence && analysis.validation_confidence !== "high") {
    y += 12;
    doc.setFontSize(FONT.tiny);
    doc.setTextColor(...COLORS.light);
    const confText =
      analysis.validation_confidence === "low"
        ? "Note: Low video confidence — some observations may be less reliable."
        : "Note: Some observations could not be fully confirmed from the footage.";
    doc.text(confText, PAGE.marginX, y);
  }

  addFooter(doc, 1);
}

// ─── Page 2: Mechanics Breakdown ────────────────────────────────────────────

function renderPhases(doc: jsPDF, analysis: AnalysisResult, startPage: number) {
  doc.addPage();
  let y = sectionHeader(doc, "Mechanics Breakdown", PAGE.marginTop + 10);
  const pageNum = { value: startPage };

  const tableBody = analysis.phases.map((p) => {
    const conf = p.confidence === "high" ? "High" : p.confidence === "medium" ? "Probable" : "Inferred";
    const issue = p.key_issue || "—";
    return [p.name, p.grade, p.observation, issue, conf];
  });

  autoTable(doc, {
    startY: y,
    margin: { left: PAGE.marginX, right: PAGE.marginX },
    head: [["Phase", "Grade", "Observation", "Key Issue", "Confidence"]],
    body: tableBody,
    styles: {
      fontSize: FONT.small,
      cellPadding: 4,
      textColor: COLORS.dark,
      lineColor: [226, 232, 240],
      lineWidth: 0.3,
    },
    headStyles: {
      fillColor: COLORS.brand,
      textColor: COLORS.white,
      fontStyle: "bold",
      fontSize: FONT.small,
    },
    columnStyles: {
      0: { cellWidth: 80, fontStyle: "bold" },
      1: { cellWidth: 32, halign: "center" },
      2: { cellWidth: "auto" },
      3: { cellWidth: 100 },
      4: { cellWidth: 48, halign: "center" },
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didParseCell: (data) => {
      // Color the grade cell
      if (data.section === "body" && data.column.index === 1) {
        const grade = String(data.cell.raw);
        data.cell.styles.textColor = gradeColor(grade);
        data.cell.styles.fontStyle = "bold";
      }
    },
    didDrawPage: () => {
      addFooter(doc, pageNum.value);
      pageNum.value++;
    },
  });

  return pageNum.value;
}

// ─── Page 3: Issues ─────────────────────────────────────────────────────────

function renderIssues(doc: jsPDF, analysis: AnalysisResult, startPage: number) {
  doc.addPage();
  let y = sectionHeader(doc, "Priority Issues", PAGE.marginTop + 10);
  const pageNum = { value: startPage };

  if (analysis.top_issues.length === 0) {
    doc.setFontSize(FONT.body);
    doc.setTextColor(...COLORS.muted);
    doc.text("No major issues identified \u2014 great mechanics!", PAGE.marginX, y + 10);
    addFooter(doc, pageNum.value);
    pageNum.value++;
    return pageNum.value;
  }

  const issueColors: [number, number, number][] = [COLORS.red, COLORS.amber, COLORS.blue];

  analysis.top_issues.forEach((issue, i) => {
    y = checkPageBreak(doc, y, 70, pageNum);

    const color = issueColors[i] || COLORS.blue;

    // Issue card background
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(PAGE.marginX, y, PAGE.contentWidth, 60, 3, 3, "F");

    // Left color bar
    doc.setFillColor(...color);
    doc.rect(PAGE.marginX, y, 3, 60, "F");

    // Priority badge
    doc.setFontSize(FONT.tiny);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...color);
    doc.text(`#${i + 1} PRIORITY`, PAGE.marginX + 12, y + 12);

    // Issue name
    doc.setFontSize(FONT.h2);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.black);
    doc.text(issue.issue, PAGE.marginX + 12, y + 24);

    // Description
    doc.setFontSize(FONT.small);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...COLORS.dark);
    const descLines = doc.splitTextToSize(issue.description, PAGE.contentWidth - 30);
    doc.text(descLines.slice(0, 2), PAGE.marginX + 12, y + 36);

    // Impact
    doc.setFontSize(FONT.tiny);
    doc.setTextColor(...COLORS.muted);
    const impactText = `Impact: ${issue.impact}`;
    const impactLines = doc.splitTextToSize(impactText, PAGE.contentWidth - 30);
    doc.text(impactLines.slice(0, 1), PAGE.marginX + 12, y + 54);

    y += 70;
  });

  addFooter(doc, pageNum.value);
  pageNum.value++;
  return pageNum.value;
}

// ─── Page 4: Drills ─────────────────────────────────────────────────────────

function renderDrills(doc: jsPDF, analysis: AnalysisResult, startPage: number) {
  doc.addPage();
  let y = sectionHeader(doc, "Recommended Drills", PAGE.marginTop + 10);
  const pageNum = { value: startPage };

  const sorted = [...analysis.drills].sort((a, b) => {
    const order = { high: 0, medium: 1, low: 2 };
    return (order[a.priority] ?? 1) - (order[b.priority] ?? 1);
  });

  sorted.forEach((drill) => {
    // Estimate needed height
    const howToLines = doc.splitTextToSize(drill.how_to, PAGE.contentWidth - 24);
    const neededHeight = 56 + howToLines.length * 10;
    y = checkPageBreak(doc, y, neededHeight, pageNum);

    // Card background
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(PAGE.marginX, y, PAGE.contentWidth, neededHeight, 3, 3, "F");

    // Priority color bar
    const pc = priorityColor(drill.priority);
    doc.setFillColor(...pc);
    doc.rect(PAGE.marginX, y, 3, neededHeight, "F");

    // Drill name
    doc.setFontSize(FONT.h2);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.black);
    doc.text(drill.name, PAGE.marginX + 12, y + 14);

    // Priority badge
    doc.setFontSize(FONT.tiny);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...pc);
    doc.text(drill.priority.toUpperCase(), PAGE.width - PAGE.marginX - 12, y + 14, {
      align: "right",
    });

    // Targets + Reps
    doc.setFontSize(FONT.small);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...COLORS.muted);
    doc.text(`Targets: ${drill.targets}  |  Reps: ${drill.reps}`, PAGE.marginX + 12, y + 26);

    // How-to
    doc.setFontSize(FONT.small);
    doc.setTextColor(...COLORS.dark);
    doc.text(howToLines, PAGE.marginX + 12, y + 38);

    // YouTube link (clickable!)
    if (drill.video_url) {
      const linkY = y + 38 + howToLines.length * 10 + 2;
      doc.setFontSize(FONT.small);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...COLORS.brand);
      const linkLabel = `\u25B6 ${drill.video_label || "Watch Demo on YouTube"}`;
      doc.textWithLink(linkLabel, PAGE.marginX + 12, linkY, { url: drill.video_url });
      // Underline
      const linkWidth = doc.getTextWidth(linkLabel);
      doc.setDrawColor(...COLORS.brand);
      doc.setLineWidth(0.3);
      doc.line(PAGE.marginX + 12, linkY + 1, PAGE.marginX + 12 + linkWidth, linkY + 1);
    }

    y += neededHeight + 6;
  });

  addFooter(doc, pageNum.value);
  pageNum.value++;
  return pageNum.value;
}

// ─── Page 5: Weekly Plan ────────────────────────────────────────────────────

function renderWeeklyPlan(doc: jsPDF, analysis: AnalysisResult, startPage: number) {
  doc.addPage();
  let y = sectionHeader(doc, "7-Day Practice Plan", PAGE.marginTop + 10);
  const pageNum = { value: startPage };

  const tableBody = analysis.weekly_plan.map((day) => {
    const activities = day.activities.map((a) => `\u2022 ${a}`).join("\n");
    return [day.day, day.focus, activities];
  });

  autoTable(doc, {
    startY: y,
    margin: { left: PAGE.marginX, right: PAGE.marginX },
    head: [["Day", "Focus", "Activities"]],
    body: tableBody,
    styles: {
      fontSize: FONT.small,
      cellPadding: 5,
      textColor: COLORS.dark,
      lineColor: [226, 232, 240],
      lineWidth: 0.3,
      overflow: "linebreak",
    },
    headStyles: {
      fillColor: COLORS.brand,
      textColor: COLORS.white,
      fontStyle: "bold",
    },
    columnStyles: {
      0: { cellWidth: 70, fontStyle: "bold" },
      1: { cellWidth: 100 },
      2: { cellWidth: "auto" },
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didDrawPage: () => {
      addFooter(doc, pageNum.value);
      pageNum.value++;
    },
  });

  return pageNum.value;
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Generate a complete PitchLab PDF report.
 * Returns a jsPDF instance you can .save() or convert to Blob.
 */
export function generateReport(analysis: AnalysisResult): jsPDF {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  doc.setFont("helvetica");

  // Page 1: Cover
  renderCover(doc, analysis);

  // Page 2+: Mechanics
  let nextPage = renderPhases(doc, analysis, 2);

  // Page 3+: Issues
  nextPage = renderIssues(doc, analysis, nextPage);

  // Page 4+: Drills
  nextPage = renderDrills(doc, analysis, nextPage);

  // Page 5+: Weekly Plan
  renderWeeklyPlan(doc, analysis, nextPage);

  return doc;
}
