/**
 * Sharing / download utilities for PitchLab reports.
 */

import type { jsPDF } from "jspdf";
import type { AnalysisResult } from "@/types/analysis";

/**
 * Build a filename for the report PDF.
 */
function reportFilename(analysis: AnalysisResult): string {
  const grade = analysis.overall_grade.replace("+", "plus").replace("-", "minus");
  const date = new Date().toISOString().slice(0, 10);
  return `PitchLab-Report-${grade}-${date}.pdf`;
}

/**
 * Trigger a browser download of the PDF.
 */
export function downloadPdf(doc: jsPDF, analysis: AnalysisResult): void {
  doc.save(reportFilename(analysis));
}

/**
 * Share the PDF using the Web Share API (mobile).
 * Returns true if shared successfully, false if unsupported or cancelled.
 */
export async function sharePdf(doc: jsPDF, analysis: AnalysisResult): Promise<boolean> {
  try {
    const blob = doc.output("blob");
    const file = new File([blob], reportFilename(analysis), { type: "application/pdf" });

    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({
        title: `PitchLab Report - ${analysis.overall_grade}`,
        text: `Pitching mechanics analysis: ${analysis.overall_grade} overall. Check out the full report!`,
        files: [file],
      });
      return true;
    }
  } catch {
    // User cancelled or API unavailable — fall through
  }
  return false;
}

/**
 * Check if native file sharing is available.
 */
export function canNativeShare(): boolean {
  if (typeof navigator === "undefined") return false;
  if (!navigator.canShare) return false;

  try {
    const testFile = new File(["test"], "test.pdf", { type: "application/pdf" });
    return navigator.canShare({ files: [testFile] });
  } catch {
    return false;
  }
}

/**
 * Copy a plain-text summary to clipboard (for quick texting/pasting).
 * Returns true on success.
 */
export async function copyTextSummary(analysis: AnalysisResult): Promise<boolean> {
  const lines: string[] = [
    `\u26BE PitchLab Analysis Report`,
    `Overall Grade: ${analysis.overall_grade}`,
    "",
    analysis.overall_summary,
    "",
  ];

  if (analysis.top_issues.length > 0) {
    lines.push("Top Issues:");
    analysis.top_issues.forEach((issue, i) => {
      lines.push(`  ${i + 1}. ${issue.issue} \u2014 ${issue.impact}`);
    });
    lines.push("");
  }

  if (analysis.drills.length > 0) {
    lines.push("Recommended Drills:");
    analysis.drills.forEach((drill) => {
      const link = drill.video_url ? ` ${drill.video_url}` : "";
      lines.push(`  \u2022 ${drill.name} (${drill.priority} priority)${link}`);
    });
    lines.push("");
  }

  lines.push(analysis.encouragement || "");
  lines.push("");
  lines.push("Generated by PitchLab \u2014 AI Mechanics Coach");

  try {
    await navigator.clipboard.writeText(lines.join("\n"));
    return true;
  } catch {
    return false;
  }
}
